version: '3'

services:
  react_app:
    image: seu_imagem_do_react
    container_name: react_app
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"    # Para HTTP
      - "443:443"  # Se você configurar HTTPS
    volumes:
      - ./build:/usr/share/nginx/html  # Certifique-se de montar o build do React no Nginx
    networks:
      - webnet
    depends_on:
      - react_app

networks:
  webnet:
    driver: bridge
