name: Build, Deploy React App to Docker Hub and Server

on:
  push:
    branches:
      - main  # Aciona o workflow quando houver push na branch 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Este é o runner do GitHub Actions para build

    steps:
      # Passo 1: Check-out do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Instalar dependências e construir frontend (React)
      - name: Install dependencies and build frontend
        run: |
          cd .\frontend\
          npm install
          npm run build

      # Passo 3: Configurar o Docker Buildx (necessário para multi-plataforma e melhores otimizações)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Passo 4: Logar no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Passo 5: Construir a imagem Docker com o código do frontend
      - name: Build Docker image
        run: |
          docker build -t melissaneves/naregua-web:latest ./frontend

      # Passo 6: Enviar a imagem para o Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push melissaneves/naregua-web:latest

  deploy:
    runs-on: self-hosted  # Usando runner self-hosted para o deploy
    needs: build-and-deploy
    steps:
      # Passo 1: Fazer login no Docker Hub
      - name: Log in to Docker Hub on self-hosted runner
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Passo 2: Puxar a imagem Docker mais recente do Docker Hub
      - name: Pull Docker image from Docker Hub
        run: |
          docker pull melissaneves/naregua-web:latest

      # Passo 3: Parar e remover qualquer container em execução com o nome 'naregua-web' (se existir)
      - name: Stop and remove existing container
        run: |
          docker ps -q --filter "name=naregua-web" | grep -q . && docker stop naregua-web && docker rm naregua-web || echo "No running container found"

      # Passo 4: Rodar o novo container no servidor
      - name: Run the Docker container
        run: |
          docker run -d --name naregua-web -p 80:80 melissaneves/naregua-web:latest
